name: LuisTakeEssentialsIX
version: 0.8.0-SNAPSHOT
main: luistakeessentialsix.luistakeessentialsix.LuisTakeEssentialsIX
api-version: 1.16
commands:
  fly:
    description: Enables the fly mode of the player who did run it.
    usage: /fly
    aliases: [flight, togglefly]
  autoitems:
    description: Displays instructions of how to enable AutoItems.
    usage: /autoitems
  heal:
    description: Fills the heal of the user who run the command.
    usage: /heal
    aliases: [healme]
  lteix:
    description: Opens LTEIX custom menu.
    usage: /lteix
  healthtroll:
    description: Sets the target health to 1
    aliases: [htroll]
    usage: /healthtroll <Player>